export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export type UPDATE_SEARCH = typeof UPDATE_SEARCH;

export const GET_TRACKS_ATTEMPT = 'GET_TRACKS_ATTEMPT';
export type GET_TRACKS_ATTEMPT = typeof GET_TRACKS_ATTEMPT;

export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export type GET_TRACKS_SUCCESS = typeof GET_TRACKS_SUCCESS;

export const GET_TRACKS_ERROR = 'GET_TRACKS_ERROR';
export type GET_TRACKS_ERROR = typeof GET_TRACKS_ERROR;

export const SORT_GRID = 'SORT_GRID';
export type SORT_GRID = typeof SORT_GRID;